const locations = [
  {
    nameEn: 'Barisal',
    nameBn: 'বরিশাল',
    districts: [
      {
        nameEn: 'Barguna',
        nameBn: 'বরগুনা',
        upazilas: [
          { nameEn: 'Amtali', nameBn: 'আমতলী' },
          { nameEn: 'Bamna', nameBn: 'বামনা' },
          { nameEn: 'Barguna Sadar', nameBn: 'বরগুনা সদর' },
          { nameEn: 'Betagi', nameBn: 'বেতাগী' },
          { nameEn: 'Patharghata', nameBn: 'পাথরঘাটা' },
          { nameEn: 'Taltali', nameBn: 'তালতলী' },
        ],
      },
      {
        nameEn: 'Barisal',
        nameBn: 'বরিশাল',
        upazilas: [
          { nameEn: 'Agailjhara', nameBn: 'আগৈলঝাড়া' },
          { nameEn: 'Babuganj', nameBn: 'বাবুগঞ্জ' },
          { nameEn: 'Bakerganj', nameBn: 'বাকেরগঞ্জ' },
          { nameEn: 'Banaripara', nameBn: 'বানারীপাড়া' },
          { nameEn: 'Barisal Sadar', nameBn: 'বরিশাল সদর', isUrban: true },
          { nameEn: 'Gaurnadi', nameBn: 'গৌরনদী' },
          { nameEn: 'Hizla', nameBn: 'হিজলা' },
          { nameEn: 'Mehendiganj', nameBn: 'মেহেন্দিগঞ্জ' },
          { nameEn: 'Muladi', nameBn: 'মুলাদী' },
          { nameEn: 'Wazirpur', nameBn: 'উজিরপুর' },
        ],
      },
      {
        nameEn: 'Bhola',
        nameBn: 'ভোলা',
        upazilas: [
          { nameEn: 'Bhola Sadar', nameBn: 'ভোলা সদর' },
          { nameEn: 'Burhanuddin', nameBn: 'বোরহানউদ্দিন' },
          { nameEn: 'Char Fasson', nameBn: 'চরফ্যাশন' },
          { nameEn: 'Daulatkhan', nameBn: 'দৌলতখান' },
          { nameEn: 'Lalmohan', nameBn: 'লালমোহন' },
          { nameEn: 'Manpura', nameBn: 'মনপুরা' },
          { nameEn: 'Tazumuddin', nameBn: 'তজুমদ্দিন' },
        ],
      },
      {
        nameEn: 'Jhalokati',
        nameBn: 'ঝালকাঠি',
        upazilas: [
          { nameEn: 'Jhalokati Sadar', nameBn: 'ঝালকাঠি সদর' },
          { nameEn: 'Kanthalia', nameBn: 'কাঁঠালিয়া' },
          { nameEn: 'Nalchity', nameBn: 'নলছিটি' },
          { nameEn: 'Rajapur', nameBn: 'রাজাপুর' },
        ],
      },
      {
        nameEn: 'Patuakhali',
        nameBn: 'পটুয়াখালী',
        upazilas: [
          { nameEn: 'Bauphal', nameBn: 'বাউফল' },
          { nameEn: 'Dashmina', nameBn: 'দশমিনা' },
          { nameEn: 'Dumki', nameBn: 'দুমকি' },
          { nameEn: 'Galachipa', nameBn: 'গলাচিপা' },
          { nameEn: 'Kalapara', nameBn: 'কলাপাড়া' },
          { nameEn: 'Mirzaganj', nameBn: 'মির্জাগঞ্জ' },
          { nameEn: 'Patuakhali Sadar', nameBn: 'পটুয়াখালী সদর' },
          { nameEn: 'Rangabali', nameBn: 'রাঙ্গাবালী' },
        ],
      },
      {
        nameEn: 'Pirojpur',
        nameBn: 'পিরোজপুর',
        upazilas: [
          { nameEn: 'Bhandaria', nameBn: 'ভাণ্ডারিয়া' },
          { nameEn: 'Indurkani', nameBn: 'ইন্দুরকানী' },
          { nameEn: 'Kawkhali', nameBn: 'কাউখালী' },
          { nameEn: 'Mathbaria', nameBn: 'মঠবাড়িয়া' },
          { nameEn: 'Nazirpur', nameBn: 'নাজিরপুর' },
          { nameEn: 'Pirojpur Sadar', nameBn: 'পিরোজপুর সদর' },
          { nameEn: 'Swarupkathi', nameBn: 'স্বরূপকাঠি' },
        ],
      },
    ],
  },
  {
    nameEn: 'Chittagong',
    nameBn: 'চট্টগ্রাম',
    districts: [
      {
        nameEn: 'Bandarban',
        nameBn: 'বান্দরবান',
        upazilas: [
          { nameEn: 'Ali Kadam', nameBn: 'আলীকদম' },
          { nameEn: 'Bandarban Sadar', nameBn: 'বান্দরবান সদর' },
          { nameEn: 'Lama', nameBn: 'লামা' },
          { nameEn: 'Naikhongchhari', nameBn: 'নাইক্ষ্যংছড়ি' },
          { nameEn: 'Rowangchhari', nameBn: 'রোয়াংছড়ি' },
          { nameEn: 'Ruma', nameBn: 'রুমা' },
          { nameEn: 'Thanchi', nameBn: 'থানচি' },
        ],
      },
      {
        nameEn: 'Brahmanbaria',
        nameBn: 'ব্রাহ্মণবাড়িয়া',
        upazilas: [
          { nameEn: 'Akhaura', nameBn: 'আখাউড়া' },
          { nameEn: 'Ashuganj', nameBn: 'আশুগঞ্জ' },
          { nameEn: 'Bancharampur', nameBn: 'বাঞ্ছারামপুর' },
          { nameEn: 'Bijoynagar', nameBn: 'বিজয়নগর' },
          { nameEn: 'Brahmanbaria Sadar', nameBn: 'ব্রাহ্মণবাড়িয়া সদর' },
          { nameEn: 'Kasba', nameBn: 'কসবা' },
          { nameEn: 'Nabinagar', nameBn: 'নবীনগর' },
          { nameEn: 'Nasirnagar', nameBn: 'নাসিরনগর' },
          { nameEn: 'Sarail', nameBn: 'সরাইল' },
        ],
      },
      {
        nameEn: 'Chandpur',
        nameBn: 'চাঁদপুর',
        upazilas: [
          { nameEn: 'Chandpur Sadar', nameBn: 'চাঁদপুর সদর' },
          { nameEn: 'Faridganj', nameBn: 'ফরিদগঞ্জ' },
          { nameEn: 'Haimchar', nameBn: 'হাইমচর' },
          { nameEn: 'Haziganj', nameBn: 'হাজীগঞ্জ' },
          { nameEn: 'Kachua', nameBn: 'কচুয়া' },
          { nameEn: 'Matlab Dakshin', nameBn: 'মতলব দক্ষিণ' },
          { nameEn: 'Matlab Uttar', nameBn: 'মতলব উত্তর' },
          { nameEn: 'Shahrasti', nameBn: 'শাহরাস্তি' },
        ],
      },
      {
        nameEn: 'Chattogram',
        nameBn: 'চট্টগ্রাম',
        upazilas: [
          { nameEn: 'Anwara', nameBn: 'আনোয়ারা' },
          { nameEn: 'Banshkhali', nameBn: 'বাঁশখালী' },
          { nameEn: 'Boalkhali', nameBn: 'বোয়ালখালী' },
          { nameEn: 'Chandanaish', nameBn: 'চন্দনাইশ' },
          { nameEn: 'Chattogram Sadar', nameBn: 'চট্টগ্রাম সদর', isUrban: true },
          { nameEn: 'Fatikchhari', nameBn: 'ফটিকছড়ি' },
          { nameEn: 'Hathazari', nameBn: 'হাটহাজারী' },
          { nameEn: 'Karnaphuli', nameBn: 'কর্ণফুলী' },
          { nameEn: 'Lohagara', nameBn: 'লোহাগাড়া' },
          { nameEn: 'Mirsharai', nameBn: 'মীরসরাই' },
          { nameEn: 'Patiya', nameBn: 'পটিয়া' },
          { nameEn: 'Rangunia', nameBn: 'রাঙ্গুনিয়া' },
          { nameEn: 'Raozan', nameBn: 'রাউজান' },
          { nameEn: 'Sandwip', nameBn: 'সন্দ্বীপ' },
          { nameEn: 'Satkania', nameBn: 'সাতকানিয়া' },
          { nameEn: 'Sitakunda', nameBn: 'সীতাকুণ্ড' },
        ],
      },
      {
        nameEn: 'Comilla',
        nameBn: 'কুমিল্লা',
        upazilas: [
          { nameEn: 'Barura', nameBn: 'বরুড়া' },
          { nameEn: 'Brahmanpara', nameBn: 'ব্রাহ্মণপাড়া' },
          { nameEn: 'Burichong', nameBn: 'বুড়িচং' },
          { nameEn: 'Chandina', nameBn: 'চান্দিনা' },
          { nameEn: 'Chauddagram', nameBn: 'চৌদ্দগ্রাম' },
          { nameEn: 'Comilla Adarsha Sadar', nameBn: 'কুমিল্লা আদর্শ সদর', isUrban: true },
          { nameEn: 'Comilla Sadar Dakshin', nameBn: 'কুমিল্লা সদর দক্ষিণ' },
          { nameEn: 'Daudkandi', nameBn: 'দাউদকান্দি' },
          { nameEn: 'Debidwar', nameBn: 'দেবিদ্বার' },
          { nameEn: 'Homna', nameBn: 'হোমনা' },
          { nameEn: 'Laksam', nameBn: 'লাকসাম' },
          { nameEn: 'Lalmai', nameBn: 'লালমাই' },
          { nameEn: 'Meghna', nameBn: 'মেঘনা' },
          { nameEn: 'Muradnagar', nameBn: 'মুরাদনগর' },
          { nameEn: 'Nangalkot', nameBn: 'নাঙ্গলকোট' },
          { nameEn: 'Titas', nameBn: 'তিতাস' },
        ],
      },
      {
        nameEn: "Cox's Bazar",
        nameBn: 'কক্সবাজার',
        upazilas: [
          { nameEn: 'Chakaria', nameBn: 'চকরিয়া' },
          { nameEn: "Cox's Bazar Sadar", nameBn: 'কক্সবাজার সদর', isUrban: true },
          { nameEn: 'Kutubdia', nameBn: 'কুতুবদিয়া' },
          { nameEn: 'Maheshkhali', nameBn: 'মহেশখালী' },
          { nameEn: 'Pekua', nameBn: 'পেকুয়া' },
          { nameEn: 'Ramu', nameBn: 'রামু' },
          { nameEn: 'Teknaf', nameBn: 'টেকনাফ' },
          { nameEn: 'Ukhia', nameBn: 'উখিয়া' },
        ],
      },
      {
        nameEn: 'Feni',
        nameBn: 'ফেনী',
        upazilas: [
          { nameEn: 'Chhagalnaiya', nameBn: 'ছাগলনাইয়া' },
          { nameEn: 'Daganbhuiyan', nameBn: 'দাগনভুঁইয়া' },
          { nameEn: 'Feni Sadar', nameBn: 'ফেনী সদর' },
          { nameEn: 'Fulgazi', nameBn: 'ফুলগাজী' },
          { nameEn: 'Parshuram', nameBn: 'পরশুরাম' },
          { nameEn: 'Sonagazi', nameBn: 'সোনাগাজী' },
        ],
      },
      {
        nameEn: 'Khagrachhari',
        nameBn: 'খাগড়াছড়ি',
        upazilas: [
          { nameEn: 'Dighinala', nameBn: 'দীঘিনালা' },
          { nameEn: 'Guimara', nameBn: 'গুইমারা' },
          { nameEn: 'Khagrachhari Sadar', nameBn: 'খাগড়াছড়ি সদর' },
          { nameEn: 'Lakshmichhari', nameBn: 'লক্ষ্মীছড়ি' },
          { nameEn: 'Mahalchhari', nameBn: 'মহালছড়ি' },
          { nameEn: 'Manikchhari', nameBn: 'মানিকছড়ি' },
          { nameEn: 'Matiranga', nameBn: 'মাটিরাঙ্গা' },
          { nameEn: 'Panchhari', nameBn: 'পানছড়ি' },
          { nameEn: 'Ramgarh', nameBn: 'রামগড়' },
        ],
      },
      {
        nameEn: 'Lakshmipur',
        nameBn: 'লক্ষ্মীপুর',
        upazilas: [
          { nameEn: 'Kamalnagar', nameBn: 'কমলনগর' },
          { nameEn: 'Lakshmipur Sadar', nameBn: 'লক্ষ্মীপুর সদর' },
          { nameEn: 'Ramganj', nameBn: 'রামগঞ্জ' },
          { nameEn: 'Ramgati', nameBn: 'রামগতি' },
          { nameEn: 'Roypur', nameBn: 'রায়পুর' },
        ],
      },
      {
        nameEn: 'Noakhali',
        nameBn: 'নোয়াখালী',
        upazilas: [
          { nameEn: 'Begumganj', nameBn: 'বেগমগঞ্জ' },
          { nameEn: 'Chatkhil', nameBn: 'চাটখিল' },
          { nameEn: 'Companiganj', nameBn: 'কোম্পানীগঞ্জ' },
          { nameEn: 'Hatiya', nameBn: 'হাতিয়া' },
          { nameEn: 'Kabirhat', nameBn: 'কবিরহাট' },
          { nameEn: 'Noakhali Sadar', nameBn: 'নোয়াখালী সদর' },
          { nameEn: 'Senbagh', nameBn: 'সেনবাগ' },
          { nameEn: 'Sonaimuri', nameBn: 'সোনাইমুড়ী' },
          { nameEn: 'Subarnachar', nameBn: 'সুবর্ণচর' },
        ],
      },
      {
        nameEn: 'Rangamati',
        nameBn: 'রাঙ্গামাটি',
        upazilas: [
          { nameEn: 'Bagaichhari', nameBn: 'বাঘাইছড়ি' },
          { nameEn: 'Barkal', nameBn: 'বরকল' },
          { nameEn: 'Belaichhari', nameBn: 'বিলাইছড়ি' },
          { nameEn: 'Juraichhari', nameBn: 'জুরাছড়ি' },
          { nameEn: 'Kaptai', nameBn: 'কাপ্তাই' },
          { nameEn: 'Kaukhali', nameBn: 'কাউখালী' },
          { nameEn: 'Langadu', nameBn: 'লংগদু' },
          { nameEn: 'Nanaiarchar', nameBn: 'নানিয়ারচর' },
          { nameEn: 'Rajasthali', nameBn: 'রাজস্থলী' },
          { nameEn: 'Rangamati Sadar', nameBn: 'রাঙ্গামাটি সদর' },
        ],
      },
    ],
  },
  {
    nameEn: 'Dhaka',
    nameBn: 'ঢাকা',
    districts: [
      {
        nameEn: 'Dhaka',
        nameBn: 'ঢাকা',
        upazilas: [
          { nameEn: 'Dhamrai', nameBn: 'ধামরাই' },
          { nameEn: 'Dohar', nameBn: 'দোহার' },
          { nameEn: 'Keraniganj', nameBn: 'কেরানীগঞ্জ' },
          { nameEn: 'Nawabganj', nameBn: 'নবাবগঞ্জ' },
          { nameEn: 'Savar', nameBn: 'সাভার', isUrban: true },
          { nameEn: 'Dhaka Sadar', nameBn: 'ঢাকা সদর', isUrban: true },
        ],
      },
      {
        nameEn: 'Faridpur',
        nameBn: 'ফরিদপুর',
        upazilas: [
          { nameEn: 'Alfadanga', nameBn: 'আলফাডাঙ্গা' },
          { nameEn: 'Bhanga', nameBn: 'ভাঙ্গা' },
          { nameEn: 'Boalmari', nameBn: 'বোয়ালমারী' },
          { nameEn: 'Charbhadrasan', nameBn: 'চরভদ্রাসন' },
          { nameEn: 'Faridpur Sadar', nameBn: 'ফরিদপুর সদর' },
          { nameEn: 'Madhukhali', nameBn: 'মধুখালী' },
          { nameEn: 'Nagarkanda', nameBn: 'নগরকান্দা' },
          { nameEn: 'Sadarpur', nameBn: 'সদরপুর' },
          { nameEn: 'Saltha', nameBn: 'সালথা' },
        ],
      },
      {
        nameEn: 'Gazipur',
        nameBn: 'গাজীপুর',
        upazilas: [
          { nameEn: 'Gazipur Sadar', nameBn: 'গাজীপুর সদর', isUrban: true },
          { nameEn: 'Kaliakoir', nameBn: 'কালিয়াকৈর' },
          { nameEn: 'Kaliganj', nameBn: 'কালীগঞ্জ' },
          { nameEn: 'Kapasia', nameBn: 'কাপাসিয়া' },
          { nameEn: 'Sreepur', nameBn: 'শ্রীপুর' },
        ],
      },
      {
        nameEn: 'Gopalganj',
        nameBn: 'গোপালগঞ্জ',
        upazilas: [
          { nameEn: 'Gopalganj Sadar', nameBn: 'গোপালগঞ্জ সদর' },
          { nameEn: 'Kashiani', nameBn: 'কাশিয়ানী' },
          { nameEn: 'Kotalipara', nameBn: 'কোটালীপাড়া' },
          { nameEn: 'Muksudpur', nameBn: 'মুকসুদপুর' },
          { nameEn: 'Tungipara', nameBn: 'টুঙ্গিপাড়া' },
        ],
      },
      {
        nameEn: 'Kishoreganj',
        nameBn: 'কিশোরগঞ্জ',
        upazilas: [
          { nameEn: 'Astagram', nameBn: 'অষ্টগ্রাম' },
          { nameEn: 'Bajitpur', nameBn: 'বাজিতপুর' },
          { nameEn: 'Bhairab', nameBn: 'ভৈরব' },
          { nameEn: 'Hossainpur', nameBn: 'হোসেনপুর' },
          { nameEn: 'Itna', nameBn: 'ইটনা' },
          { nameEn: 'Karimganj', nameBn: 'করিমগঞ্জ' },
          { nameEn: 'Katiadi', nameBn: 'কটিয়াদী' },
          { nameEn: 'Kishoreganj Sadar', nameBn: 'কিশোরগঞ্জ সদর' },
          { nameEn: 'Kuliarchar', nameBn: 'কুলিয়ারচর' },
          { nameEn: 'Mithamain', nameBn: 'মিঠামইন' },
          { nameEn: 'Nikli', nameBn: 'নিকলী' },
          { nameEn: 'Pakundia', nameBn: 'পাকুন্দিয়া' },
          { nameEn: 'Tarail', nameBn: 'তাড়াইল' },
        ],
      },
      {
        nameEn: 'Madaripur',
        nameBn: 'মাদারীপুর',
        upazilas: [
          { nameEn: 'Kalkini', nameBn: 'কালকিনি' },
          { nameEn: 'Madaripur Sadar', nameBn: 'মাদারীপুর সদর' },
          { nameEn: 'Rajoir', nameBn: 'রাজৈর' },
          { nameEn: 'Shibchar', nameBn: 'শিবচর' },
        ],
      },
      {
        nameEn: 'Manikganj',
        nameBn: 'মানিকগঞ্জ',
        upazilas: [
          { nameEn: 'Daulatpur', nameBn: 'দৌলতপুর' },
          { nameEn: 'Ghior', nameBn: 'ঘিওর' },
          { nameEn: 'Harirampur', nameBn: 'হরিরামপুর' },
          { nameEn: 'Manikganj Sadar', nameBn: 'মানিকগঞ্জ সদর' },
          { nameEn: 'Saturia', nameBn: 'সাটুরিয়া' },
          { nameEn: 'Shivalaya', nameBn: 'শিবালয়' },
          { nameEn: 'Singair', nameBn: 'সিঙ্গাইর' },
        ],
      },
      {
        nameEn: 'Munshiganj',
        nameBn: 'মুন্সিগঞ্জ',
        upazilas: [
          { nameEn: 'Gazaria', nameBn: 'গজারিয়া' },
          { nameEn: 'Louhajang', nameBn: 'লৌহজং' },
          { nameEn: 'Munshiganj Sadar', nameBn: 'মুন্সিগঞ্জ সদর' },
          { nameEn: 'Sirajdikhan', nameBn: 'সিরাজদিখান' },
          { nameEn: 'Sreenagar', nameBn: 'শ্রীনগর' },
          { nameEn: 'Tongibari', nameBn: 'টংগিবাড়ি' },
        ],
      },
      {
        nameEn: 'Narayanganj',
        nameBn: 'নারায়ণগঞ্জ',
        upazilas: [
          { nameEn: 'Araihazar', nameBn: 'আড়াইহাজার' },
          { nameEn: 'Bandar', nameBn: 'বন্দর' },
          { nameEn: 'Narayanganj Sadar', nameBn: 'নারায়ণগঞ্জ সদর', isUrban: true },
          { nameEn: 'Rupganj', nameBn: 'রূপগঞ্জ' },
          { nameEn: 'Sonargaon', nameBn: 'সোনারগাঁও' },
        ],
      },
      {
        nameEn: 'Narsingdi',
        nameBn: 'নরসিংদী',
        upazilas: [
          { nameEn: 'Belabo', nameBn: 'বেলাবো' },
          { nameEn: 'Monohardi', nameBn: 'মনোহরদী' },
          { nameEn: 'Narsingdi Sadar', nameBn: 'নরসিংদী সদর' },
          { nameEn: 'Palash', nameBn: 'পলাশ' },
          { nameEn: 'Raipura', nameBn: 'রায়পুরা' },
          { nameEn: 'Shibpur', nameBn: 'শিবপুর' },
        ],
      },
      {
        nameEn: 'Rajbari',
        nameBn: 'রাজবাড়ী',
        upazilas: [
          { nameEn: 'Baliakandi', nameBn: 'বালিয়াকান্দি' },
          { nameEn: 'Goalandaghat', nameBn: 'গোয়ালন্দ ঘাট' },
          { nameEn: 'Kalukhali', nameBn: 'কালুখালী' },
          { nameEn: 'Pangsha', nameBn: 'পাংশা' },
          { nameEn: 'Rajbari Sadar', nameBn: 'রাজবাড়ী সদর' },
        ],
      },
      {
        nameEn: 'Shariatpur',
        nameBn: 'শরীয়তপুর',
        upazilas: [
          { nameEn: 'Bhedarganj', nameBn: 'ভেদরগঞ্জ' },
          { nameEn: 'Damudya', nameBn: 'ডামুড্যা' },
          { nameEn: 'Gosairhat', nameBn: 'গোসাইরহাট' },
          { nameEn: 'Jajira', nameBn: 'জাজিরা' },
          { nameEn: 'Naria', nameBn: 'নড়িয়া' },
          { nameEn: 'Shariatpur Sadar', nameBn: 'শরীয়তপুর সদর' },
        ],
      },
      {
        nameEn: 'Tangail',
        nameBn: 'টাঙ্গাইল',
        upazilas: [
          { nameEn: 'Basail', nameBn: 'বাসাইল' },
          { nameEn: 'Bhuapur', nameBn: 'ভুয়াপুর' },
          { nameEn: 'Delduar', nameBn: 'দেলদুয়ার' },
          { nameEn: 'Dhanbari', nameBn: 'ধনবাড়ী' },
          { nameEn: 'Ghatail', nameBn: 'ঘাটাইল' },
          { nameEn: 'Gopalpur', nameBn: 'গোপালপুর' },
          { nameEn: 'Kalihati', nameBn: 'কালিহাতী' },
          { nameEn: 'Madhupur', nameBn: 'মধুপুর' },
          { nameEn: 'Mirzapur', nameBn: 'মির্জাপুর' },
          { nameEn: 'Nagarpur', nameBn: 'নাগরপুর' },
          { nameEn: 'Sakhipur', nameBn: 'সখীপুর' },
          { nameEn: 'Tangail Sadar', nameBn: 'টাঙ্গাইল সদর' },
        ],
      },
    ],
  },
  {
    nameEn: 'Khulna',
    nameBn: 'খুলনা',
    districts: [
      {
        nameEn: 'Bagerhat',
        nameBn: 'বাগেরহাট',
        upazilas: [
          { nameEn: 'Bagerhat Sadar', nameBn: 'বাগেরহাট সদর' },
          { nameEn: 'Chitalmari', nameBn: 'চিতলমারী' },
          { nameEn: 'Fakirhat', nameBn: 'ফকিরহাট' },
          { nameEn: 'Kachua', nameBn: 'কচুয়া' },
          { nameEn: 'Mollahat', nameBn: 'মোল্লাহাট' },
          { nameEn: 'Mongla', nameBn: 'মোংলা' },
          { nameEn: 'Morrelganj', nameBn: 'মোড়েলগঞ্জ' },
          { nameEn: 'Rampal', nameBn: 'রামপাল' },
          { nameEn: 'Sarankhola', nameBn: 'শরণখোলা' },
        ],
      },
      {
        nameEn: 'Chuadanga',
        nameBn: 'চুয়াডাঙ্গা',
        upazilas: [
          { nameEn: 'Alamdanga', nameBn: 'আলমডাঙ্গা' },
          { nameEn: 'Chuadanga Sadar', nameBn: 'চুয়াডাঙ্গা সদর' },
          { nameEn: 'Damurhuda', nameBn: 'দামুড়হুদা' },
          { nameEn: 'Jibannagar', nameBn: 'জীবননগর' },
        ],
      },
      {
        nameEn: 'Jashore',
        nameBn: 'যশোর',
        upazilas: [
          { nameEn: 'Abhaynagar', nameBn: 'অভয়নগর' },
          { nameEn: 'Bagherpara', nameBn: 'বাঘারপাড়া' },
          { nameEn: 'Chaugacha', nameBn: 'চৌগাছা' },
          { nameEn: 'Jashore Sadar', nameBn: 'যশোর সদর', isUrban: true },
          { nameEn: 'Jhikargacha', nameBn: 'ঝিকরগাছা' },
          { nameEn: 'Keshobpur', nameBn: 'কেশবপুর' },
          { nameEn: 'Manirampur', nameBn: 'মনিরামপুর' },
          { nameEn: 'Sharsha', nameBn: 'শার্শা' },
        ],
      },
      {
        nameEn: 'Jhenaidah',
        nameBn: 'ঝিনাইদহ',
        upazilas: [
          { nameEn: 'Harinakunda', nameBn: 'হরিণাকুণ্ডু' },
          { nameEn: 'Jhenaidah Sadar', nameBn: 'ঝিনাইদহ সদর' },
          { nameEn: 'Kaliganj', nameBn: 'কালীগঞ্জ' },
          { nameEn: 'Kotchandpur', nameBn: 'কোটচাঁদপুর' },
          { nameEn: 'Maheshpur', nameBn: 'মহেশপুর' },
          { nameEn: 'Shailkupa', nameBn: 'শৈলকুপা' },
        ],
      },
      {
        nameEn: 'Khulna',
        nameBn: 'খুলনা',
        upazilas: [
          { nameEn: 'Batiaghata', nameBn: 'বটিয়াঘাটা' },
          { nameEn: 'Dacope', nameBn: 'দাকোপ' },
          { nameEn: 'Dighalia', nameBn: 'দিঘলিয়া' },
          { nameEn: 'Dumuria', nameBn: 'ডুমুরিয়া' },
          { nameEn: 'Khulna Sadar', nameBn: 'খুলনা সদর', isUrban: true },
          { nameEn: 'Koyra', nameBn: 'কয়রা' },
          { nameEn: 'Paikgachha', nameBn: 'পাইকগাছা' },
          { nameEn: 'Phultala', nameBn: 'ফুলতলা' },
          { nameEn: 'Rupsha', nameBn: 'রূপসা' },
          { nameEn: 'Terokhada', nameBn: 'তেরখাদা' },
        ],
      },
      {
        nameEn: 'Kushtia',
        nameBn: 'কুষ্টিয়া',
        upazilas: [
          { nameEn: 'Bheramara', nameBn: 'ভেড়ামারা' },
          { nameEn: 'Daulatpur', nameBn: 'দৌলতপুর' },
          { nameEn: 'Khoksa', nameBn: 'খোকসা' },
          { nameEn: 'Kumarkhali', nameBn: 'কুমারখালী' },
          { nameEn: 'Kushtia Sadar', nameBn: 'কুষ্টিয়া সদর' },
          { nameEn: 'Mirpur', nameBn: 'মিরপুর' },
        ],
      },
      {
        nameEn: 'Magura',
        nameBn: 'মাগুরা',
        upazilas: [
          { nameEn: 'Magura Sadar', nameBn: 'মাগুরা সদর' },
          { nameEn: 'Mohammadpur', nameBn: 'মোহাম্মদপুর' },
          { nameEn: 'Shalikha', nameBn: 'শালিখা' },
          { nameEn: 'Sreepur', nameBn: 'শ্রীপুর' },
        ],
      },
      {
        nameEn: 'Meherpur',
        nameBn: 'মেহেরপুর',
        upazilas: [
          { nameEn: 'Gangni', nameBn: 'গাংনী' },
          { nameEn: 'Meherpur Sadar', nameBn: 'মেহেরপুর সদর' },
          { nameEn: 'Mujib Nagar', nameBn: 'মুজিবনগর' },
        ],
      },
      {
        nameEn: 'Narail',
        nameBn: 'নড়াইল',
        upazilas: [
          { nameEn: 'Kalia', nameBn: 'কালিয়া' },
          { nameEn: 'Lohagara', nameBn: 'লোহাগড়া' },
          { nameEn: 'Narail Sadar', nameBn: 'নড়াইল সদর' },
        ],
      },
      {
        nameEn: 'Satkhira',
        nameBn: 'সাতক্ষীরা',
        upazilas: [
          { nameEn: 'Assasuni', nameBn: 'আশাশুনি' },
          { nameEn: 'Debhata', nameBn: 'দেবহাটা' },
          { nameEn: 'Kalaroa', nameBn: 'কলারোয়া' },
          { nameEn: 'Kaliganj', nameBn: 'কালীগঞ্জ' },
          { nameEn: 'Satkhira Sadar', nameBn: 'সাতক্ষীরা সদর' },
          { nameEn: 'Shyamnagar', nameBn: 'শ্যামনগর' },
          { nameEn: 'Tala', nameBn: 'তালা' },
        ],
      },
    ],
  },
  {
    nameEn: 'Mymensingh',
    nameBn: 'ময়মনসিংহ',
    districts: [
      {
        nameEn: 'Jamalpur',
        nameBn: 'জামালপুর',
        upazilas: [
          { nameEn: 'Bakshiganj', nameBn: 'বকশীগঞ্জ' },
          { nameEn: 'Dewanganj', nameBn: 'দেওয়ানগঞ্জ' },
          { nameEn: 'Islampur', nameBn: 'ইসলামপুর' },
          { nameEn: 'Jamalpur Sadar', nameBn: 'জামালপুর সদর' },
          { nameEn: 'Madarganj', nameBn: 'মাদারগঞ্জ' },
          { nameEn: 'Melandaha', nameBn: 'মেলান্দহ' },
          { nameEn: 'Sarishabari', nameBn: 'সরিষাবাড়ী' },
        ],
      },
      {
        nameEn: 'Mymensingh',
        nameBn: 'ময়মনসিংহ',
        upazilas: [
          { nameEn: 'Bhaluka', nameBn: 'ভালুকা' },
          { nameEn: 'Dhobaura', nameBn: 'ধোবাউড়া' },
          { nameEn: 'Fulbaria', nameBn: 'ফুলবাড়িয়া' },
          { nameEn: 'Gaffargaon', nameBn: 'গফরগাঁও' },
          { nameEn: 'Gauripur', nameBn: 'গৌরীপুর' },
          { nameEn: 'Haluaghat', nameBn: 'হালুয়াঘাট' },
          { nameEn: 'Ishwarganj', nameBn: 'ঈশ্বরগঞ্জ' },
          { nameEn: 'Muktagachha', nameBn: 'মুক্তাগাছা' },
          { nameEn: 'Mymensingh Sadar', nameBn: 'ময়মনসিংহ সদর', isUrban: true },
          { nameEn: 'Nandail', nameBn: 'নান্দাইল' },
          { nameEn: 'Phulpur', nameBn: 'ফুলপুর' },
          { nameEn: 'Trishal', nameBn: 'ত্রিশাল' },
        ],
      },
      {
        nameEn: 'Netrokona',
        nameBn: 'নেত্রকোণা',
        upazilas: [
          { nameEn: 'Atpara', nameBn: 'আটপাড়া' },
          { nameEn: 'Barhatta', nameBn: 'বারহাট্টা' },
          { nameEn: 'Durgapur', nameBn: 'দুর্গাপুর' },
          { nameEn: 'Kalmakanda', nameBn: 'কলমাকান্দা' },
          { nameEn: 'Kendua', nameBn: 'কেন্দুয়া' },
          { nameEn: 'Khaliajuri', nameBn: 'খালিয়াজুরী' },
          { nameEn: 'Madan', nameBn: 'মদন' },
          { nameEn: 'Mohanganj', nameBn: 'মোহনগঞ্জ' },
          { nameEn: 'Netrokona Sadar', nameBn: 'নেত্রকোণা সদর' },
          { nameEn: 'Purbadhala', nameBn: 'পূর্বধলা' },
        ],
      },
      {
        nameEn: 'Sherpur',
        nameBn: 'শেরপুর',
        upazilas: [
          { nameEn: 'Jhenaigati', nameBn: 'ঝিনাইগাতী' },
          { nameEn: 'Nakla', nameBn: 'নকলা' },
          { nameEn: 'Nalitabari', nameBn: 'নালিতাবাড়ী' },
          { nameEn: 'Sherpur Sadar', nameBn: 'শেরপুর সদর' },
          { nameEn: 'Sreebordi', nameBn: 'শ্রীবরদী' },
        ],
      },
    ],
  },
  {
    nameEn: 'Rajshahi',
    nameBn: 'রাজশাহী',
    districts: [
      {
        nameEn: 'Bogura',
        nameBn: 'বগুড়া',
        upazilas: [
          { nameEn: 'Adamdighi', nameBn: 'আদমদীঘি' },
          { nameEn: 'Bogura Sadar', nameBn: 'বগুড়া সদর', isUrban: true },
          { nameEn: 'Dhunat', nameBn: 'ধুনট' },
          { nameEn: 'Dhupchanchia', nameBn: 'ধুপচাঁচিয়া' },
          { nameEn: 'Gabtali', nameBn: 'গাবতলী' },
          { nameEn: 'Kahaloo', nameBn: 'কাহালু' },
          { nameEn: 'Nandigram', nameBn: 'নন্দীগ্রাম' },
          { nameEn: 'Sariakandi', nameBn: 'সারিয়াকান্দি' },
          { nameEn: 'Shajahanpur', nameBn: 'শাজাহানপুর' },
          { nameEn: 'Sherpur', nameBn: 'শেরপুর' },
          { nameEn: 'Shibganj', nameBn: 'শিবগঞ্জ' },
          { nameEn: 'Sonatala', nameBn: 'সোনাতলা' },
        ],
      },
      {
        nameEn: 'Chapai Nawabganj',
        nameBn: 'চাঁপাইনবাবগঞ্জ',
        upazilas: [
          { nameEn: 'Bholahat', nameBn: 'ভোলাহাট' },
          { nameEn: 'Chapai Nawabganj Sadar', nameBn: 'চাঁপাইনবাবগঞ্জ সদর' },
          { nameEn: 'Gomastapur', nameBn: 'গোমস্তাপুর' },
          { nameEn: 'Nachole', nameBn: 'নাচোল' },
          { nameEn: 'Shibganj', nameBn: 'শিবগঞ্জ' },
        ],
      },
      {
        nameEn: 'Joypurhat',
        nameBn: 'জয়পুরহাট',
        upazilas: [
          { nameEn: 'Akkelpur', nameBn: 'আক্কেলপুর' },
          { nameEn: 'Joypurhat Sadar', nameBn: 'জয়পুরহাট সদর' },
          { nameEn: 'Kalai', nameBn: 'কালাই' },
          { nameEn: 'Khetlal', nameBn: 'ক্ষেতলাল' },
          { nameEn: 'Panchbibi', nameBn: 'পাঁচবিবি' },
        ],
      },
      {
        nameEn: 'Naogaon',
        nameBn: 'নওগাঁ',
        upazilas: [
          { nameEn: 'Atrai', nameBn: 'আত্রাই' },
          { nameEn: 'Badalgachhi', nameBn: 'বদলগাছী' },
          { nameEn: 'Dhamoirhat', nameBn: 'ধামইরহাট' },
          { nameEn: 'Mahadebpur', nameBn: 'মহাদেবপুর' },
          { nameEn: 'Manda', nameBn: 'মান্দা' },
          { nameEn: 'Naogaon Sadar', nameBn: 'নওগাঁ সদর' },
          { nameEn: 'Niamatpur', nameBn: 'নিয়ামতপুর' },
          { nameEn: 'Patnitala', nameBn: 'পত্নীতলা' },
          { nameEn: 'Porsha', nameBn: 'পোরশা' },
          { nameEn: 'Raninagar', nameBn: 'রানীনগর' },
          { nameEn: 'Sapahar', nameBn: 'সাপাহার' },
        ],
      },
      {
        nameEn: 'Natore',
        nameBn: 'নাটোর',
        upazilas: [
          { nameEn: 'Bagatipara', nameBn: 'বাগাতিপাড়া' },
          { nameEn: 'Baraigram', nameBn: 'বড়াইগ্রাম' },
          { nameEn: 'Gurudaspur', nameBn: 'গুরুদাসপুর' },
          { nameEn: 'Lalpur', nameBn: 'লালপুর' },
          { nameEn: 'Naldanga', nameBn: 'নলদাঙ্গা' },
          { nameEn: 'Natore Sadar', nameBn: 'নাটোর সদর' },
          { nameEn: 'Singra', nameBn: 'সিংড়া' },
        ],
      },
      {
        nameEn: 'Pabna',
        nameBn: 'পাবনা',
        upazilas: [
          { nameEn: 'Atgharia', nameBn: 'আটঘরিয়া' },
          { nameEn: 'Bera', nameBn: 'বেড়া' },
          { nameEn: 'Bhangura', nameBn: 'ভাঙ্গুড়া' },
          { nameEn: 'Chatmohar', nameBn: 'চাটমোহর' },
          { nameEn: 'Faridpur', nameBn: 'ফরিদপুর' },
          { nameEn: 'Ishwardi', nameBn: 'ঈশ্বরদী' },
          { nameEn: 'Pabna Sadar', nameBn: 'পাবনা সদর' },
          { nameEn: 'Santhia', nameBn: 'সাঁথিয়া' },
          { nameEn: 'Sujanagar', nameBn: 'সুজানগর' },
        ],
      },
      {
        nameEn: 'Rajshahi',
        nameBn: 'রাজশাহী',
        upazilas: [
          { nameEn: 'Bagha', nameBn: 'বাঘা' },
          { nameEn: 'Bagmara', nameBn: 'বাগমারা' },
          { nameEn: 'Charghat', nameBn: 'চারঘাট' },
          { nameEn: 'Durgapur', nameBn: 'দুর্গাপুর' },
          { nameEn: 'Godagari', nameBn: 'গোদাগাড়ী' },
          { nameEn: 'Mohanpur', nameBn: 'মোহনপুর' },
          { nameEn: 'Paba', nameBn: 'পবা' },
          { nameEn: 'Puthia', nameBn: 'পুঠিয়া' },
          { nameEn: 'Rajshahi Sadar', nameBn: 'রাজশাহী সদর', isUrban: true },
          { nameEn: 'Tanore', nameBn: 'তানোর' },
        ],
      },
      {
        nameEn: 'Sirajganj',
        nameBn: 'সিরাজগঞ্জ',
        upazilas: [
          { nameEn: 'Belkuchi', nameBn: 'বেলকুচি' },
          { nameEn: 'Chauhali', nameBn: 'চৌহালী' },
          { nameEn: 'Enayetpur', nameBn: 'এনায়েতপুর' },
          { nameEn: 'Kamarkhanda', nameBn: 'কামারখন্দ' },
          { nameEn: 'Kazipur', nameBn: 'কাজীপুর' },
          { nameEn: 'Raiganj', nameBn: 'রায়গঞ্জ' },
          { nameEn: 'Shahjadpur', nameBn: 'শাহজাদপুর' },
          { nameEn: 'Sirajganj Sadar', nameBn: 'সিরাজগঞ্জ সদর' },
          { nameEn: 'Tarash', nameBn: 'তাড়াশ' },
          { nameEn: 'Ullapara', nameBn: 'উল্লাপাড়া' },
        ],
      },
    ],
  },
  {
    nameEn: 'Rangpur',
    nameBn: 'রংপুর',
    districts: [
      {
        nameEn: 'Dinajpur',
        nameBn: 'দিনাজপুর',
        upazilas: [
          { nameEn: 'Birampur', nameBn: 'বিরামপুর' },
          { nameEn: 'Birganj', nameBn: 'বিরগঞ্জ' },
          { nameEn: 'Biral', nameBn: 'বীরল' },
          { nameEn: 'Bochaganj', nameBn: 'বোচাগঞ্জ' },
          { nameEn: 'Chirirbandar', nameBn: 'চিরিরবন্দর' },
          { nameEn: 'Dinajpur Sadar', nameBn: 'দিনাজপুর সদর' },
          { nameEn: 'Fulbari', nameBn: 'ফুলবাড়ী' },
          { nameEn: 'Ghoraghat', nameBn: 'ঘোড়াঘাট' },
          { nameEn: 'Hakimpur', nameBn: 'হাকিমপুর' },
          { nameEn: 'Kaharole', nameBn: 'কাহারোল' },
          { nameEn: 'Khansama', nameBn: 'খানসামা' },
          { nameEn: 'Nawabganj', nameBn: 'নবাবগঞ্জ' },
          { nameEn: 'Parbatipur', nameBn: 'পার্বতীপুর' },
        ],
      },
      {
        nameEn: 'Gaibandha',
        nameBn: 'গাইবান্ধা',
        upazilas: [
          { nameEn: 'Fulchhari', nameBn: 'ফুলছড়ি' },
          { nameEn: 'Gaibandha Sadar', nameBn: 'গাইবান্ধা সদর' },
          { nameEn: 'Gobindaganj', nameBn: 'গোবিন্দগঞ্জ' },
          { nameEn: 'Palashbari', nameBn: 'পলাশবাড়ী' },
          { nameEn: 'Sadullapur', nameBn: 'সাদুল্লাপুর' },
          { nameEn: 'Saghatta', nameBn: 'সাঘাটা' },
          { nameEn: 'Sundarganj', nameBn: 'সুন্দরগঞ্জ' },
        ],
      },
      {
        nameEn: 'Kurigram',
        nameBn: 'কুড়িগ্রাম',
        upazilas: [
          { nameEn: 'Bhurungamari', nameBn: 'ভুরুঙ্গামারী' },
          { nameEn: 'Char Rajibpur', nameBn: 'চর রাজিবপুর' },
          { nameEn: 'Chilmari', nameBn: 'চিলমারী' },
          { nameEn: 'Kurigram Sadar', nameBn: 'কুড়িগ্রাম সদর' },
          { nameEn: 'Nageshwari', nameBn: 'নাগেশ্বরী' },
          { nameEn: 'Phulbari', nameBn: 'ফুলবাড়ী' },
          { nameEn: 'Rajarhat', nameBn: 'রাজারহাট' },
          { nameEn: 'Raomari', nameBn: 'রৌমারী' },
          { nameEn: 'Ulipur', nameBn: 'উলিপুর' },
        ],
      },
      {
        nameEn: 'Lalmonirhat',
        nameBn: 'লালমনিরহাট',
        upazilas: [
          { nameEn: 'Aditmari', nameBn: 'আদিতমারী' },
          { nameEn: 'Hatibandha', nameBn: 'হাতীবান্ধা' },
          { nameEn: 'Kaliganj', nameBn: 'কালীগঞ্জ' },
          { nameEn: 'Lalmonirhat Sadar', nameBn: 'লালমনিরহাট সদর' },
          { nameEn: 'Patgram', nameBn: 'পাটগ্রাম' },
        ],
      },
      {
        nameEn: 'Nilphamari',
        nameBn: 'নীলফামারী',
        upazilas: [
          { nameEn: 'Dimla', nameBn: 'ডিমলা' },
          { nameEn: 'Domar', nameBn: 'ডোমার' },
          { nameEn: 'Jaldhaka', nameBn: 'জলঢাকা' },
          { nameEn: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ' },
          { nameEn: 'Nilphamari Sadar', nameBn: 'নীলফামারী সদর' },
          { nameEn: 'Saidpur', nameBn: 'সৈয়দপুর', isUrban: true },
        ],
      },
      {
        nameEn: 'Panchagarh',
        nameBn: 'পঞ্চগড়',
        upazilas: [
          { nameEn: 'Atwari', nameBn: 'আটোয়ারী' },
          { nameEn: 'Boda', nameBn: 'বোদা' },
          { nameEn: 'Debiganj', nameBn: 'দেবীগঞ্জ' },
          { nameEn: 'Panchagarh Sadar', nameBn: 'পঞ্চগড় সদর' },
          { nameEn: 'Tetulia', nameBn: 'তেঁতুলিয়া' },
        ],
      },
      {
        nameEn: 'Rangpur',
        nameBn: 'রংপুর',
        upazilas: [
          { nameEn: 'Badarganj', nameBn: 'বদরগঞ্জ' },
          { nameEn: 'Gangachara', nameBn: 'গঙ্গাচড়া' },
          { nameEn: 'Kaunia', nameBn: 'কাউনিয়া' },
          { nameEn: 'Mithapukur', nameBn: 'মিঠাপুকুর' },
          { nameEn: 'Pirgachha', nameBn: 'পীরগাছা' },
          { nameEn: 'Pirganj', nameBn: 'পীরগঞ্জ' },
          { nameEn: 'Rangpur Sadar', nameBn: 'রংপুর সদর', isUrban: true },
          { nameEn: 'Taraganj', nameBn: 'তারাগঞ্জ' },
        ],
      },
      {
        nameEn: 'Thakurgaon',
        nameBn: 'ঠাকুরগাঁও',
        upazilas: [
          { nameEn: 'Baliadangi', nameBn: 'বালিয়াডাঙ্গী' },
          { nameEn: 'Haripur', nameBn: 'হরিপুর' },
          { nameEn: 'Pirganj', nameBn: 'পীরগঞ্জ' },
          { nameEn: 'Ranisankail', nameBn: 'রানীশংকৈল' },
          { nameEn: 'Thakurgaon Sadar', nameBn: 'ঠাকুরগাঁও সদর' },
        ],
      },
    ],
  },
  {
    nameEn: 'Sylhet',
    nameBn: 'সিলেট',
    districts: [
      {
        nameEn: 'Habiganj',
        nameBn: 'হবিগঞ্জ',
        upazilas: [
          { nameEn: 'Ajmiriganj', nameBn: 'আজমিরীগঞ্জ' },
          { nameEn: 'Bahubal', nameBn: 'বাহুবল' },
          { nameEn: 'Baniachong', nameBn: 'বানিয়াচং' },
          { nameEn: 'Chunarughat', nameBn: 'চুনারুঘাট' },
          { nameEn: 'Habiganj Sadar', nameBn: 'হবিগঞ্জ সদর' },
          { nameEn: 'Lakhai', nameBn: 'লাখাই' },
          { nameEn: 'Madhabpur', nameBn: 'মাধবপুর' },
          { nameEn: 'Nabiganj', nameBn: 'নবীগঞ্জ' },
        ],
      },
      {
        nameEn: 'Moulvibazar',
        nameBn: 'মৌলভীবাজার',
        upazilas: [
          { nameEn: 'Barlekha', nameBn: 'বড়লেখা' },
          { nameEn: 'Juri', nameBn: 'জুড়ী' },
          { nameEn: 'Kamalganj', nameBn: 'কমলগঞ্জ' },
          { nameEn: 'Kulaura', nameBn: 'কুলাউড়া' },
          { nameEn: 'Moulvibazar Sadar', nameBn: 'মৌলভীবাজার সদর' },
          { nameEn: 'Rajnagar', nameBn: 'রাজনগর' },
          { nameEn: 'Sreemangal', nameBn: 'শ্রীমঙ্গল' },
        ],
      },
      {
        nameEn: 'Sunamganj',
        nameBn: 'সুনামগঞ্জ',
        upazilas: [
          { nameEn: 'Bishwamvarpur', nameBn: 'বিশ্বম্ভরপুর' },
          { nameEn: 'Chhatak', nameBn: 'ছাতক' },
          { nameEn: 'Derai', nameBn: 'দিরাই' },
          { nameEn: 'Dharmapasha', nameBn: 'ধর্মপাশা' },
          { nameEn: 'Doarabazar', nameBn: 'দোয়ারাবাজার' },
          { nameEn: 'Jagannathpur', nameBn: 'জগন্নাথপুর' },
          { nameEn: 'Jamalganj', nameBn: 'জামালগঞ্জ' },
          { nameEn: 'Sullah', nameBn: 'শাল্লা' },
          { nameEn: 'Sunamganj Sadar', nameBn: 'সুনামগঞ্জ সদর' },
          { nameEn: 'Tahirpur', nameBn: 'তাহিরপুর' },
        ],
      },
      {
        nameEn: 'Sylhet',
        nameBn: 'সিলেট',
        upazilas: [
          { nameEn: 'Balaganj', nameBn: 'বালাগঞ্জ' },
          { nameEn: 'Beani Bazar', nameBn: 'বিয়ানীবাজার' },
          { nameEn: 'Bishwanath', nameBn: 'বিশ্বনাথ' },
          { nameEn: 'Companiganj', nameBn: 'কোম্পানিগঞ্জ' },
          { nameEn: 'Fenchuganj', nameBn: 'ফেঞ্চুগঞ্জ' },
          { nameEn: 'Golapganj', nameBn: 'গোলাপগঞ্জ' },
          { nameEn: 'Gowainghat', nameBn: 'গোয়াইনঘাট' },
          { nameEn: 'Jaintiapur', nameBn: 'জৈন্তাপুর' },
          { nameEn: 'Kanaighat', nameBn: 'কানাইঘাট' },
          { nameEn: 'Osmani Nagar', nameBn: 'ওসমানী নগর' },
          { nameEn: 'South Surma', nameBn: 'দক্ষিণ সুরমা' },
          { nameEn: 'Sylhet Sadar', nameBn: 'সিলেট সদর', isUrban: true },
          { nameEn: 'Zakiganj', nameBn: 'জকিগঞ্জ' },
        ],
      },
    ],
  },
]

async function seedLocations(prisma) {
  console.log('Seeding Bangladesh administrative locations...')

  // Delete in FK dependency order (most dependent first)
  await prisma.childMilestone.deleteMany()
  await prisma.sleepSession.deleteMany()
  await prisma.activitySession.deleteMany()
  await prisma.childVaccination.deleteMany()
  await prisma.growthMeasurement.deleteMany()
  await prisma.illnessRecord.deleteMany()
  await prisma.child.deleteMany()
  await prisma.parent.deleteMany()
  await prisma.healthWorker.deleteMany()
  await prisma.upazilla.deleteMany()
  await prisma.district.deleteMany()
  await prisma.division.deleteMany()

  let divisionCount = 0
  let districtCount = 0
  let upazillaCount = 0

  for (const divisionData of locations) {
    const { districts, ...divisionFields } = divisionData

    const division = await prisma.division.create({
      data: {
        ...divisionFields,
        districts: {
          create: districts.map(({ upazilas, ...districtFields }) => ({
            ...districtFields,
            upazilas: {
              create: upazilas.map(({ isUrban = false, ...upazillaFields }) => ({
                ...upazillaFields,
                isUrban,
              })),
            },
          })),
        },
      },
      include: {
        districts: { include: { upazilas: true } },
      },
    })

    divisionCount += 1
    districtCount += division.districts.length
    upazillaCount += division.districts.reduce((sum, d) => sum + d.upazilas.length, 0)

    console.log(`  ✓ ${division.nameEn} — ${division.districts.length} districts`)
  }

  console.log(`  Divisions : ${divisionCount}`)
  console.log(`  Districts : ${districtCount}`)
  console.log(`  Upazilas  : ${upazillaCount}`)
}

module.exports = { seedLocations }
